preferred-supported-locales: [ en, ru, ky, uk ]
synthetic-package: false
output-dir: ./lib/l10n/generated
arb-dir: ./lib/l10n
template-arb-file: intl_en.arb
output-localization-file: flutter_json_schema_form_localizations.dart
output-class: FlutterJsonSchemaFormLocalizations